package com.iattend.app.ui.theme

import androidx.compose.ui.graphics.Color

// ---- Cashiro accent palette (10 of 24) copied verbatim from Reference_Repos/Cashiro/presentation/ui/theme/Color.kt ----
// Catppuccin Latte (light)
val Latte_Rosewater = Color(0xFFD29182)
val Latte_Rosewater_secondary = Color(0xFF87CD94)
val Latte_Rosewater_tertiary = Color(0xFFA79CDC)
val Latte_Blue = Color(0xFF007aff)
val Latte_Blue_secondary = Color(0xFF6866B8)
val Latte_Blue_tertiary = Color(0xFF6DC468)
val Latte_Green = Color(0xFF549E43)
val Latte_Green_secondary = Color(0xFF4C7F5C)
val Latte_Green_tertiary = Color(0xFF7BA02B)
val Latte_Mauve = Color(0xFF8D5DCB)
val Latte_Mauve_secondary = Color(0xFFBA68C0)
val Latte_Mauve_tertiary = Color(0xFF6168C7)
val Latte_Peach = Color(0xFFE25C0E)
val Latte_Peach_secondary = Color(0xFFE3C81D)
val Latte_Peach_tertiary = Color(0xFFE2B20E)
// Rosé Pine Dawn (light)
val Dawn_Rose = Color(0xFFD7827E)
val Dawn_Rose_secondary = Color(0xFFD4A373)
val Dawn_Rose_tertiary = Color(0xFFC49B9B)
val Dawn_Iris = Color(0xFF907AA9)
val Dawn_Iris_secondary = Color(0xFF7E9CB9)
val Dawn_Iris_tertiary = Color(0xFFB4637A)
val Dawn_Pine = Color(0xFF286983)
val Dawn_Pine_secondary = Color(0xFF56949F)
val Dawn_Pine_tertiary = Color(0xFF3B8686)
val Dawn_Gold = Color(0xFFEA9D34)
val Dawn_Gold_secondary = Color(0xFFD7827E)
val Dawn_Gold_tertiary = Color(0xFFC4956A)
val Dawn_Foam = Color(0xFF56949F)
val Dawn_Foam_secondary = Color(0xFF286983)
val Dawn_Foam_tertiary = Color(0xFF6E9A6E)
// Catppuccin Macchiato dim (dark fallback-light)
val Macchiato_Rosewater_dim = Color(0xFFE1A091)
val Macchiato_Rosewater_dim_secondary = Color(0xFF9EDDAA)
val Macchiato_Rosewater_dim_tertiary = Color(0xFFAA9EDD)
val Macchiato_Blue_dim = Color(0xFF007aff)
val Macchiato_Blue_dim_secondary = Color(0xFF9190E6)
val Macchiato_Blue_dim_tertiary = Color(0xFF93B887)
val Macchiato_Green_dim = Color(0xFF93B887)
val Macchiato_Green_dim_secondary = Color(0xFF7CAD8F)
val Macchiato_Green_dim_tertiary = Color(0xFFD0D57B)
val Macchiato_Mauve_dim = Color(0xFFBC93F3)
val Macchiato_Mauve_dim_secondary = Color(0xFFE398CE)
val Macchiato_Mauve_dim_tertiary = Color(0xFF939AF3)
val Macchiato_Peach_dim = Color(0xFFF5A97f)
val Macchiato_Peach_dim_secondary = Color(0xFFE6DA92)
val Macchiato_Peach_dim_tertiary = Color(0xFFDF9192)
// Macchiato dark primaries
val Macchiato_Rosewater = Color(0xFFEACBC4)
val Macchiato_Blue = Color(0xFF3395FF)
val Macchiato_Green = Color(0xFF93B887)
val Macchiato_Mauve = Color(0xFFBC93F3)
val Macchiato_Peach = Color(0xFFf5a97f)
// Rosé Pine Main (dark)
val RosePine_Rose = Color(0xFFEBBCBA)
val RosePine_Rose_secondary = Color(0xFFF6C177)
val RosePine_Rose_tertiary = Color(0xFFE0AFA0)
val RosePine_Iris = Color(0xFFC4A7E7)
val RosePine_Iris_secondary = Color(0xFF9CCFD8)
val RosePine_Iris_tertiary = Color(0xFFEB6F92)
val RosePine_Pine = Color(0xFF31748F)
val RosePine_Pine_secondary = Color(0xFF9CCFD8)
val RosePine_Pine_tertiary = Color(0xFF569F9F)
val RosePine_Gold = Color(0xFFF6C177)
val RosePine_Gold_secondary = Color(0xFFEBBCBA)
val RosePine_Gold_tertiary = Color(0xFFE0B08A)
val RosePine_Foam = Color(0xFF9CCFD8)
val RosePine_Foam_secondary = Color(0xFF31748F)
val RosePine_Foam_tertiary = Color(0xFF8EC9A0)
// Shared dawn/rose surfaces
val Dawn_Background = Color(0xFFF5EDE5)
val Dawn_OnBackground = Color(0xFF575279)
val Dawn_Surface_Base = Color(0xFFF8F5F5)
val Dawn_OnSurface = Color(0xFF575279)
val Dawn_SurfaceVariant = Color(0xFFF2E9E1)
val Dawn_OnSurfaceVariant = Color(0xFF6E6A86)
val RosePine_Background = Color(0xFF191724)
val RosePine_OnBackground = Color(0xFFE0DEF4)
val RosePine_Surface_Base = Color(0xFF1F1D2E)
val RosePine_OnSurface = Color(0xFFE0DEF4)
val RosePine_SurfaceVariant = Color(0xFF26233A)
val RosePine_OnSurfaceVariant = Color(0xFF908CAA)

// Forest Green Palette - Light
val ForestPrimary = Color(0xFF006D3A)
val ForestOnPrimary = Color(0xFFFFFFFF)
val ForestPrimaryContainer = Color(0xFF99F6B4)
val ForestOnPrimaryContainer = Color(0xFF00210D)

val ForestSecondary = Color(0xFF4F6354)
val ForestOnSecondary = Color(0xFFFFFFFF)
val ForestSecondaryContainer = Color(0xFFD2E8D5)
val ForestOnSecondaryContainer = Color(0xFF0C1F13)

val ForestTertiary = Color(0xFF3B6470)
val ForestOnTertiary = Color(0xFFFFFFFF)
val ForestTertiaryContainer = Color(0xFFBEEAF7)
val ForestOnTertiaryContainer = Color(0xFF001F26)

val ForestError = Color(0xFFBA1A1A)
val ForestOnError = Color(0xFFFFFFFF)
val ForestErrorContainer = Color(0xFFFFDAD6)
val ForestOnErrorContainer = Color(0xFF410002)

val ForestBackground = Color(0xFFFBFDF8)
val ForestOnBackground = Color(0xFF191C1A)
val ForestSurface = Color(0xFFFBFDF8)
val ForestOnSurface = Color(0xFF191C1A)
val ForestSurfaceVariant = Color(0xFFDCE5DB)
val ForestOnSurfaceVariant = Color(0xFF414942)
val ForestOutline = Color(0xFF717971)

// Forest Green Palette - Dark
val ForestPrimaryDark = Color(0xFF7DD99A)
val ForestOnPrimaryDark = Color(0xFF00391C)
val ForestPrimaryContainerDark = Color(0xFF00522B)
val ForestOnPrimaryContainerDark = Color(0xFF99F6B4)

val ForestSecondaryDark = Color(0xFFB6CCB9)
val ForestOnSecondaryDark = Color(0xFF213527)
val ForestSecondaryContainerDark = Color(0xFF374B3D)
val ForestOnSecondaryContainerDark = Color(0xFFD2E8D5)

val ForestTertiaryDark = Color(0xFFA2CEDB)
val ForestOnTertiaryDark = Color(0xFF013540)
val ForestTertiaryContainerDark = Color(0xFF214C58)
val ForestOnTertiaryContainerDark = Color(0xFFBEEAF7)

val ForestErrorDark = Color(0xFFFFB4AB)
val ForestOnErrorDark = Color(0xFF690005)
val ForestErrorContainerDark = Color(0xFF93000A)
val ForestOnErrorContainerDark = Color(0xFFFFDAD6)

val ForestBackgroundDark = Color(0xFF191C1A)
val ForestOnBackgroundDark = Color(0xFFE1E3DF)
val ForestSurfaceDark = Color(0xFF191C1A)
val ForestOnSurfaceDark = Color(0xFFE1E3DF)
val ForestSurfaceVariantDark = Color(0xFF414942)
val ForestOnSurfaceVariantDark = Color(0xFFC0C9BF)
val ForestOutlineDark = Color(0xFF8B938A)

// Old colors kept for compatibility if needed, though we'll likely replace their usage
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
